config/routes.rb
Rails.application.routes.draw do
  root to: "messages#index"
  resources :messages
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  
end

app/models/message.rb
class Message < ApplicationRecord
  before_create :send_message

private
  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, :only => [:show, :edit, :destroy, :update]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "You've got yourself a new contact!"
      redirect_to contacts_path
    else
      flash[:alert] = "Error. Error. Error."
      redirect_to 'new'
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      flash[:notice] = "You've got a friend in #{@contact.name}. (Contact Updated)"
      redirect_to @contact
    else
      flash[:alert] = "Error. Error. Error."
      redirect_to :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

private
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :number)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all
    @contacts = Contact.all
    @weather_object = FindHumidity.new("97210")
    @humidity = @weather_object.get_humidity()
  end

  def new
    @message = Message.new
  end

  def show

  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Saved!"
      redirect_to root_path
    else
      render 'new'
    end
  end

private
  def get_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_for contact do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn' %>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<article class="panel">
  <header>
    <h1>Contacts</h1>
    <% @contacts.each do |contact| %>
      <p>
        <%= contact.name %>
      </p>
      <p>
        <%= contact.number %>
      </p>
    <% end %>


    <h4>New Contact</h4>
    <%= render 'form', contact: Contact.new %>
  </header>
</article>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="card">
  <div class="card-block">
    <div class="card-title">
      <%= @contact.name %>
    </div>
    <div class="card-text">
      <%= @contact.number %>
    </div>
    <%= link_to "Edit", edit_contact_path(@contact) %>
    <%= link_to "Delete", contact_path(@contact), data: {
      method: "delete",
      confirm: "Are you sure?"
      } %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
  <div id="footer">
    <ul class="copyright">
      <li>&copy; Untitled.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
    </ul>
  </div>

app/views/layouts/_nav.html.erb
<!-- Nav -->
  <nav id="nav">
    <%= link_to "<span>Messages</span>".html_safe, root_path ,
    class: "icon fa-envelope #{'active' if current_page?(root_path)}" %>
    <%= link_to "<span>Contacts</span>".html_safe, contacts_path ,
    class: "icon fa-address-card #{'active' if current_page?(contacts_path)}" %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/css/astral.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" id="wrapper">
      <%= render 'layouts/nav' %>
      <div id="main">
        <%=  flash[:notice] %>
        <%=  flash[:alert] %>

        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  		<script src="/js/skel.min.js"></script>
  		<script src="/js/skel-viewport.min.js"></script>
  		<script src="/js/util.js"></script>
  		<script src="/js/main.js"></script>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for message do |f| %>
  <div class="form-group">
    <%= f.label :to %>
    <%= f.text_field :to, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :from %>
    <%= f.text_field :from, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn' %>
<% end %>

app/views/messages/index.html.erb
<article class="panel">
  <header>
    <h1>Messages</h1>
    <% @messages.each do |message| %>
      <p>
        <%= message.body %> (<%= message.status %>  )
      </p>

    <% end %>

    <div id="contacts">
      <h4>Contacts:</h4>
      <% @contacts.each do |contact| %>
        <p>
          <button id="add-contact-<%= contact.id %>" class="btn add-btn" data-contact-number="<%= contact.number %>">+</button>
          <%= contact.name %>
        </p>
      <% end %>
    </div>

    <p> Humidity: <%= @humidity %> </p>

    <h4>New Message</h4>
    <%= render 'form', message: Message.new %>
  </header>

</article>

app/views/messages/new.html.erb
<%= render "form", message: @message %>